### ISSUE TITLE
only first item shows "readmore" on flatlist 0.44

### ISSUE THREAD

**Issue by deathnopool** [expo/react-native-read-more-text#8] opened 2017-05-15 02:23 UTC
only first item shows "readmore" on flatlist 0.44

**Comment by mbenjamin618** [comment] 2017-05-16 20:41
Having the same problem with RN's listView

**Comment by DarkHollow** [comment] 2017-08-02 21:03
@mbenjamin618 How do you unmount and mount a component like a view?

**Comment by Ridwansameer** [comment] 2018-08-15 11:28
Hey! Was running into the same issue and managed to find a fix.

Simply pass in a "key" prop to the ReadMore Component, and give it something unique like an ID for whatever you are rendering in the FlatList.

Hope this help.

**Comment by ashryOlarm** [comment] 2019-09-04 14:43
I changed the condition in the index.js to be:
if (!showAllText) {
      if (this.props.renderTruncatedFooter) {
        return this.props.renderTruncatedFooter(this._handlePressReadMore);
      }

      return (
        <Text style={styles.button} onPress={this._handlePressReadMore}>
          Read more
        </Text>
      );
    } else if (showAllText) {
      if (this.props.renderRevealedFooter) {
        return this.props.renderRevealedFooter(this._handlePressReadLess);
      }

      return (
        <Text style={styles.button} onPress={this._handlePressReadLess}>
          Hide
        </Text>
      );
    }

It will show "Read more" always even if text lines less than numberOfLines, But it works fine.

**Comment by deepas96** [comment] 2019-12-16 10:27
Still struggling with this issue

**Comment by Ridwansameer** [comment] 2019-12-16 10:30
> Still struggling with this issue

Did you try my solution posted above?

**Comment by deepas96** [comment] 2019-12-18 06:13
> > Still struggling with this issue
> 
> Did you try my solution posted above?

Yes.. I have tried passing key prop and passed {index} to it.. But it didn't work

**Comment by eriveltonelias** [comment] 2020-01-31 02:42
Can someone provide a runnable repro on https://snack.expo.io please ?

**Comment by eriveltonelias** [comment] 2020-02-05 10:39
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.

**Closed by eriveltonelias** 2020-02-05 10:39 UTC
Labels: need repro

**Comment by yokada0807** [comment] 2020-03-03 08:50
The same issue happened to me too
But strangely, it happens only on Android devices in my case.
I tried @Ridwansameer 's solution and it didn't work for me...

**Comment by eriveltonelias** [comment] 2020-03-04 09:37
Can you provide a reproducible example @yokada0807 ?

**Comment by r3b311i0n** [comment] 2020-05-14 21:53
I was just running into similar issues. I sort of worked around it by:

- Removing nearly all the code in `async componentDidMount()`

```js
 async componentDidMount() {
    this._isMounted = true;
  }
```

- And using `onLayout`

```jsx
      <View>
        <Text
          numberOfLines={measured && !showAllText ? numberOfLines : 0}
          onLayout={event => {
            if (!this._isMounted) {
              return;
            }
            if (!this.fullHeight) {
              this.fullHeight = event.nativeEvent.layout.height;
              this.setState({ measured: true });
              return;
            }
            const limitedHeight = event.nativeEvent.layout.height;
            if (this.fullHeight > limitedHeight) {
              this.setState({ shouldShowReadMore: true }, () => {
                this.props.onReady && this.props.onReady();
              });
            } else {
              this.props.onReady && this.props.onReady();
            }
          }}
          style={this.props.textStyle}
        >
          {this.props.children}
        </Text>

        {this._maybeRenderReadMore()}
      </View>
```

Fork [here](https://github.com/r3b311i0n/react-native-read-more-text). But this won't respond well to dynamically changing `numberOfLines` but I also created a [functional version](https://github.com/r3b311i0n/react-native-read-more-text/blob/master/functional.js) which *seems* to work fine with dynamic `numberOfLines`.

**Comment by rohitkum28** [comment] 2020-06-14 12:46
@eriveltonelias 
I am still facing this issue. Here is a [reproducible expo link](https://snack.expo.io/TVWgIyp1T). As you can see the issue is only happening in Android and works fine on iOS.

**Comment by muhammadarsal** [comment] 2020-08-27 12:05
Thanks for the awesome library. Would really appreciate if someone could look into this issue.

**Comment by loukrath** [comment] 2020-09-03 07:57
@rohitkum28 and @muhammadarsal , I face the same issue by using Flatlist. 

> Option 1: Change to **ScrollView**

> Option 2: Add prop **removeClippedSubviews={false}** 

Hope this solution helpful for you guys.

**Comment by subhadippramanik** [comment] 2020-09-24 16:38
Same issue here.. 
@loukrath I tried Option 2, but didn't work.

**Comment by loukrath** [comment] 2020-10-01 07:27
> Same issue here..
> @loukrath I tried Option 2, but didn't work.

@subhadippramanik how about option 1

**Comment by vineelk8** [comment] 2021-04-16 18:01
> @rohitkum28 and @muhammadarsal , I face the same issue by using Flatlist.
> 
> > Option 1: Change to **ScrollView**
> 
> > Option 2: Add prop **removeClippedSubviews={false}**
> 
> Hope this solution helpful for you guys.

Option 2 worked from me, thanks
